
project_id = "avarecipe"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

# メール送信テストサーバー (Inbucket)
[inbucket]
enabled = true 
port = 54324
smtp_port = 54325 

[studio]
# 管理画面
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"


# 分析・ログ収集 (クラッシュしたため, 無効化)
[analytics]
enabled = false

# リアルタイム通信 (Websocket)
[realtime]
enabled = false

# Edge Functions (Honoを使うので不要)
[edge_runtime]
enabled = false

# 画像変換・リサイズ機能 
[storage.image_transformation]
enabled = false
